const actions = {
    FETCH_LIST_OF_USERS_REQUEST: 'FETCH_LIST_OF_USERS_REQUEST',
    FETCH_LIST_OF_USERS_SUCCESS: 'FETCH_LIST_OF_USERS_SUCCESS',
    FETCH_LIST_OF_USERS_FAILURE: 'FETCH_LIST_OF_USERS_FAILURE',

    fetchUserListRequest: () => ({
        type: actions.FETCH_LIST_OF_USERS_REQUEST,
    }),

    FETCH_LIST_OF_POSTS_REQUEST: 'FETCH_LIST_OF_POSTS_REQUEST',
    FETCH_LIST_OF_POSTS_SUCCESS: 'FETCH_LIST_OF_POSTS_SUCCESS',
    FETCH_LIST_OF_POSTS_FAILURE: 'FETCH_LIST_OF_POSTS_FAILURE',

    fetchPostListRequest: () => ({
        type: actions.FETCH_LIST_OF_POSTS_REQUEST,
    }),

    FETCH_LIST_OF_ALBUMS_REQUEST: 'FETCH_LIST_OF_ALBUMS_REQUEST',
    FETCH_LIST_OF_ALBUMS_SUCCESS: 'FETCH_LIST_OF_ALBUMS_SUCCESS',
    FETCH_LIST_OF_ALBUMS_FAILURE: 'FETCH_LIST_OF_ALBUMS_FAILURE',

    fetchAlbumListRequest: () => ({
        type: actions.FETCH_LIST_OF_ALBUMS_REQUEST,
    }),
    
    FETCH_LIST_OF_PHOTOS_REQUEST: 'FETCH_LIST_OF_PHOTOS_REQUEST',
    FETCH_LIST_OF_PHOTOS_SUCCESS: 'FETCH_LIST_OF_PHOTOS_SUCCESS',
    FETCH_LIST_OF_PHOTOS_FAILURE: 'FETCH_LIST_OF_PHOTOS_FAILURE',

    fetchPhotoListRequest: () => ({
        type: actions.FETCH_LIST_OF_PHOTOS_REQUEST,
    }),

};
export default actions;
